### ISSUE TITLE
Update deprecated output usage

### ISSUE THREAD

**Issue by XSlemX** [stacc/github-workflow-actions#12]
The reusable workflows have outdated set output usage which causes this error: `The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see:` https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The link shows examples of how to update to new pattern.

**Comment by AuStien** [comment]
Resolved in https://github.com/stacc/github-workflow-actions/pull/14
