### ISSUE TITLE
Type in job name

### ISSUE THREAD

**Issue by XSlemX** [stacc/github-workflow-actions#13]
Reusable workflow `reusable_report-junit` has one job named `pull-request`. This makes for odd display when used.

Proposed change to: `report-junit-test`

**Comment by AuStien** [comment]
Seconded.

For consistency's sake every `reusable_report-*` job should be called `report-*`.

Suggested name changes:
- `reusable_report-deployment`: `pull-request` => `report-deployment`
- `reusable_report-junit`: `pull-request` => `report-junit-test`
- `reusable_report-pull-request`: `pull-request` => `report-pull-request`
- `reusable_report-snyk`: `snyk` => `report-snyk`
