### ISSUE TITLE
Use stacc.azurecr.io as container registry

### ISSUE THREAD

**Issue by AuStien** [stacc/github-workflow-actions#16]
There is a goal to go away from using JFrog and only use `stacc.azurecr.io`.
Considering most services and customer projects will have their workflows rewritten (and Helm Charts change hosted repo) this is a great opportunity to make the transition.

**Comment by AuStien** [comment]
Wait, is JFrog even used?

**Comment by XSlemX** [comment]
JFrog is only mentioned and used here when building flow-setup (if using the old flow-setup-deployer). It will be ripped out when the need is no longer there.

**Comment by AuStien** [comment]
`stacc.azurecr.io` is already used as container registry
